# Problem Statement
Objective:
To analyze Company X's performance from 2014 to 2018, focusing on identifying key revenue and profit drivers across products, sales channels, and geographic regions. The goal is to uncover seasonal trends, detect performance outliers, and evaluate alignment with budget targets.

Scope of Analysis:

. Pinpoint the top-performing products, channels, and regions contributing to growth.

. Identify seasonal patterns and anomalies that impact financial performance.

. Compare actual performance against budget expectations to measure efficiency.

. Leverage insights to recommend strategies for:

. Pricing optimization

. Promotional planning

. Market expansion

. Risk mitigation through diversification

Outcome:
Actionable insights to drive sustainable revenue growth, improve profit margins, and reduce dependence on specific markets or segments, thereby enhancing overall business resilience.

# Step 1: Import Libraries and Set Visualization Style

This section loads essential Python libraries (`pandas`, `numpy`, `matplotlib`, and `seaborn`) for data analysis and visualization. We also apply consistent styling using `plt.rcParams` and define a helper function `heading()` for section headers.

In [2]:
# importing libs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

%matplotlib inline

sns.set_theme(style='whitegrid', palette='pastel')  # softer palette
plt.rcParams['figure.figsize'] = (12, 6)            # slightly wider for better visuals
plt.rcParams['axes.titlesize'] = 14                 # increase title size
plt.rcParams['axes.labelsize'] = 12                 # increase label size
plt.rcParams['figure.dpi'] = 120                    # higher resolution visuals

plt.rcParams['font.family'] = 'Arial'

def heading(title):
    print(f"\n📌 {title.upper()}\n{'=' * (len(title) + 2)}")

# Step 2: Load Excel Dataset

We load the multi-sheet Excel file and assign each sheet (like 'Sales Orders', 'Customers', etc.) to a separate DataFrame for easier handling and analysis.

In [4]:
sheets = pd.read_excel(r"D:\Data Analytics\End to End Data analytics Project\Regional Sales Dataset.xlsx", sheet_name = None)

In [5]:
print(sheets)

{'Sales Orders':         OrderNumber  OrderDate  Customer Name Index      Channel  \
0       SO - 000225 2014-01-01                  126    Wholesale
1      SO - 0003378 2014-01-01                   96  Distributor
2      SO - 0005126 2014-01-01                    8    Wholesale
3      SO - 0005614 2014-01-01                   42       Export
4      SO - 0005781 2014-01-01                   73    Wholesale
...             ...        ...                  ...          ...
64099  SO - 0007573 2018-02-28                   74    Wholesale
64100  SO - 0007706 2018-02-28                   51       Export
64101  SO - 0007718 2018-02-28                  136  Distributor
64102  SO - 0008084 2018-02-28                  158  Distributor
64103  SO - 0008654 2018-02-28                   22  Distributor

      Currency Code Warehouse Code  Delivery Region Index  \
0               USD         AXW291                    364
1               USD         AXW291                    488
2               USD         AXW291                    155
3               USD         AXW291                    473
4               USD         AXW291                    256
...             ...            ...                    ...
64099           USD         AXW291                    825
64100           USD         NXH382                    444
64101           USD         AXW291                    312
64102           USD         AXW291                    737
64103           USD         AXW291                    807

       Product Description Index  Order Quantity  Unit Price  Line Total  \
0                             27               6      2499.1     14994.6
1                             20              11      2351.7     25868.7
2                             26               6       978.2      5869.2
3                              7               7      2338.3     16368.1
4                              8               8      2291.4     18331.2
...                          ...             ...         ...         ...
64099                         26              12      1815.7     21788.4
64100                         21               6       864.3      5185.8
64101                         13              11      3953.0     43483.0
64102                         20               7      3959.7     27717.9
64103                         15               8       998.3      7986.4

       Total Unit Cost
0             1824.343
1             1269.918
2              684.740
3             1028.852
4             1260.270
...                ...
64099          980.478
64100          579.081
64101         2648.510
64102         2930.178
64103          848.555

[64104 rows x 12 columns], 'Customers':      Customer Index Customer Names
0                 1  Geiss Company
1                 2  Jaxbean Group
2                 3     Ascend Ltd
3                 4      Eire Corp
4                 5   Blogtags Ltd
..              ...            ...
170             171   Accord Group
171             172   BB17 Company
172             173          H Ltd
173             174   Tekfly Group
174             175   SHISEIDO Ltd

[175 rows x 2 columns], 'Regions':       id        name                                   county state_code  \
0      1      Auburn                               Lee County         AL
1      2  Birmingham           Shelby County/Jefferson County         AL
2      3     Decatur           Limestone County/Morgan County         AL
3      4      Dothan  Dale County/Houston County/Henry County         AL
4      5      Hoover           Shelby County/Jefferson County         AL
..   ...         ...                                      ...        ...
989  990      Racine                            Racine County         WI
990  991    Waukesha                          Waukesha County         WI
991  992  West Allis                         Milwaukee County         WI
992  993      Casper                           Natrona County         WY
993  994    Cheyenne                           Laramie County         WY

         state  type  latitude  longitude  area_code  population  households  \
0      Alabama  City  32.60986  -85.48078        334       62059       21767
1      Alabama  City  33.52744  -86.79905        205      212461       89972
2      Alabama  City  34.57332  -86.99214        256       55437       22294
3      Alabama  City  31.23370  -85.40682        334       68567       25913
4      Alabama  City  33.37695  -86.80558        205       84848       32789
..         ...   ...       ...        ...        ...         ...         ...
989  Wisconsin  City  42.72613  -87.78285        262       77742       29851
990  Wisconsin  City  43.01168  -88.23148        262       71970       28331
991  Wisconsin  City  43.01668  -88.00703        414       60620       27457
992    Wyoming  City  42.86663 -106.31308        307       60285       23814
993    Wyoming  City  41.13998 -104.82025        307       63335       25130

     median_income  land_area  water_area        time_zone
0            38342  152375113     2646161  America/Chicago
1            31061  378353942     6591013  America/Chicago
2            41496  141006257    17594716  America/Chicago
3            42426  232166237      835468  America/Chicago
4            77146  122016784     2553332  America/Chicago
..             ...        ...         ...              ...
989          41455   40111757     8282116  America/Chicago
990          59547   65856921      700602  America/Chicago
991          45221   29480532       60789  America/Chicago
992          57790   68507280      911081   America/Denver
993          58219   69964749      282335   America/Denver

[994 rows x 15 columns], 'State Regions':        Column1               Column2    Column3
0   State Code                 State     Region
1           AL               Alabama      South
2           AR              Arkansas      South
3           AZ               Arizona       West
4           CA            California       West
5           CO              Colorado       West
6           CT           Connecticut  Northeast
7           DC  District of Columbia      South
8           DE              Delaware      South
9           FL               Florida      South
10          GA               Georgia      South
11          HI                Hawaii       West
12          IA                  Iowa    Midwest
13          ID                 Idaho       West
14          IL              Illinois    Midwest
15          IN               Indiana    Midwest
16          KS                Kansas    Midwest
17          KY              Kentucky      South
18          LA             Louisiana      South
19          MA         Massachusetts  Northeast
20          MD              Maryland      South
21          ME                 Maine  Northeast
22          MI              Michigan    Midwest
23          MN             Minnesota    Midwest
24          MO              Missouri    Midwest
25          MS           Mississippi      South
26          MT               Montana       West
27          NC        North Carolina      South
28          ND          North Dakota    Midwest
29          NE              Nebraska    Midwest
30          NH         New Hampshire  Northeast
31          NJ            New Jersey  Northeast
32          NM            New Mexico       West
33          NV                Nevada       West
34          NY              New York  Northeast
35          OH                  Ohio    Midwest
36          OK              Oklahoma      South
37          OR                Oregon       West
38          PA          Pennsylvania  Northeast
39          RI          Rhode Island  Northeast
40          SC        South Carolina      South
41          SD          South Dakota    Midwest
42          TN             Tennessee      South
43          TX                 Texas      South
44          UT                  Utah       West
45          VA              Virginia      South
46          WA            Washington       West
47          WI             Wisconsin    Midwest
48          WY               Wyoming       West, 'Products':     Index Product Name
0       1    Product 1
1       2    Product 2
2       3    Product 3
3       4    Product 4
4       5    Product 5
5       6    Product 6
6       7    Product 7
7       8    Product 8
8       9    Product 9
9      10   Product 10
10     11   Product 11
11     12   Product 12
12     13   Product 13
13     14   Product 14
14     15   Product 15
15     16   Product 16
16     17   Product 17
17     18   Product 18
18     19   Product 19
19     20   Product 20
20     21   Product 21
21     22   Product 22
22     23   Product 23
23     24   Product 24
24     25   Product 25
25     26   Product 26
26     27   Product 27
27     28   Product 28
28     29   Product 29
29     30   Product 30, '2017 Budgets':    Product Name  2017 Budgets
0     Product 1   3016489.209
1     Product 2   3050087.565
2     Product 3   2642352.432
3     Product 4   2885560.824
4     Product 5   3925424.542
5     Product 6   1672229.416
6     Product 7    889737.555
7     Product 8   1085037.329
8     Product 9    710415.405
9    Product 10    864331.624
10   Product 11   1230458.484
11   Product 12   1356976.996
12   Product 13   3720639.645
13   Product 14   4028698.409
14   Product 15   3299478.315
15   Product 16   2062061.144
16   Product 17   2119616.824
17   Product 18   2309499.045
18   Product 19   1645841.600
19   Product 20   2067108.120
20   Product 21    959899.218
21   Product 22    663601.902
22   Product 23   1135815.758
23   Product 24    756557.970
24   Product 25   5342315.484
25   Product 26   5685138.270
26   Product 27    964940.231
27   Product 28   1003867.767
28   Product 29    594471.570
29   Product 30   1011609.684}

In [6]:
# Assign dataframes to each sheet

df_sales = sheets['Sales Orders']
df_customers = sheets['Customers']
df_products = sheets['Products']
df_regions = sheets['Regions']
df_state_reg = sheets['State Regions']
df_budgets = sheets['2017 Budgets']

In [7]:
df_sales.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270

# Step 3: Inspect Dataset Dimensions

We check the shape (rows, columns) of each dataset to understand the size of each table. This gives us a basic idea of what we’re working with.

In [9]:
print ("df_sales.shape:", (df_sales.shape))
print ("df_products.shape:", (df_products.shape))
print ("df_customers.shape:", (df_customers.shape))
print ("df_regions.shape:", (df_regions.shape))
print ("df_state_reg.shape:", (df_state_reg.shape))
print ("df_budgets.shape:", (df_budgets.shape))

df_sales.shape: (64104, 12)
df_products.shape: (30, 2)
df_customers.shape: (175, 2)
df_regions.shape: (994, 15)
df_state_reg.shape: (49, 3)
df_budgets.shape: (30, 2)

# Step 4: Preview the Data

We display the first few rows of the main tables to get familiar with the column names and the kind of data present.

In [11]:
df_products.head()

   Index Product Name
0      1    Product 1
1      2    Product 2
2      3    Product 3
3      4    Product 4
4      5    Product 5

In [12]:
df_customers.head()

   Customer Index Customer Names
0               1  Geiss Company
1               2  Jaxbean Group
2               3     Ascend Ltd
3               4      Eire Corp
4               5   Blogtags Ltd

In [13]:
df_regions.head()

,id,name,county,state_code,state,type,latitude,longitude,area_code,population,households,median_income,land_area,water_area,time_zone
0,1,Auburn,Lee County,AL,Alabama,City,32.60986,-85.48078,334,62059,21767,38342,152375113,2646161,America/Chicago
1,2,Birmingham,Shelby County/Jefferson County,AL,Alabama,City,33.52744,-86.79905,205,212461,89972,31061,378353942,6591013,America/Chicago
2,3,Decatur,Limestone County/Morgan County,AL,Alabama,City,34.57332,-86.99214,256,55437,22294,41496,141006257,17594716,America/Chicago
3,4,Dothan,Dale County/Houston County/Henry County,AL,Alabama,City,31.23370,-85.40682,334,68567,25913,42426,232166237,835468,America/Chicago
4,5,Hoover,Shelby County/Jefferson County,AL,Alabama,City,33.37695,-86.80558,205,84848,32789,77146,122016784,2553332,America/Chicago

In [14]:
df_state_reg.head()
# would need to remove column1,2,3

      Column1     Column2 Column3
0  State Code       State  Region
1          AL     Alabama   South
2          AR    Arkansas   South
3          AZ     Arizona    West
4          CA  California    West

In [15]:
# alternative 
# df_state_reg = pd.read_excel(r"D:\Data Analytics\End to End Data analytics Project\Regional Sales Dataset.xlsx", sheet_name="State Regions", header=1)

In [16]:
df_budgets.head()

  Product Name  2017 Budgets
0    Product 1   3016489.209
1    Product 2   3050087.565
2    Product 3   2642352.432
3    Product 4   2885560.824
4    Product 5   3925424.542

# Step 5: Clean `df_state_reg` Table

The actual column names for `df_state_reg` are stored in the first row. So we:
1. Extract the first row as column headers,
2. Assign it to the columns,
3. Drop the first row and reset the index.

In [18]:
new_header = df_state_reg.iloc[0]                   
df_state_reg.columns = new_header                   
df_state_reg = df_state_reg[1:].reset_index(drop=True)  
df_state_reg.head()

# alternative 
# df_state_reg = pd.read_excel(r"D:\Data Analytics\End to End Data analytics Project\Regional Sales Dataset.xlsx", sheet_name="State Regions", header=1)

0 State Code       State Region
0         AL     Alabama  South
1         AR    Arkansas  South
2         AZ     Arizona   West
3         CA  California   West
4         CO    Colorado   West

# Step 6: Check for Missing Values

We inspect missing (null) values in the key tables like `df_sales` and `df_regions`. This helps us decide if any data imputation or cleaning is needed later.

In [20]:
df_sales.isnull().sum()

OrderNumber                  0
OrderDate                    0
Customer Name Index          0
Channel                      0
Currency Code                0
Warehouse Code               0
Delivery Region Index        0
Product Description Index    0
Order Quantity               0
Unit Price                   0
Line Total                   0
Total Unit Cost              0
dtype: int64

In [21]:
df_customers.isnull().sum()

Customer Index    0
Customer Names    0
dtype: int64

In [22]:
df_regions.isnull().sum()

id               0
name             0
county           0
state_code       0
state            0
type             0
latitude         0
longitude        0
area_code        0
population       0
households       0
median_income    0
land_area        0
water_area       0
time_zone        0
dtype: int64

In [23]:
df_state_reg.isnull().sum()

0
State Code    0
State         0
Region        0
dtype: int64

In [24]:
df_products.isnull().sum()

Index           0
Product Name    0
dtype: int64

In [25]:
df_budgets.isnull().sum()

Product Name    0
2017 Budgets    0
dtype: int64

# Step 7: Cleaning and Wrangling

In [27]:
# merge with customers 
df = df_sales.merge(
    df_customers,
    how = 'left',
    left_on = 'Customer Name Index',
    right_on = 'Customer Index'
)

In [28]:
df

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost,Customer Index,Customer Names
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343,126,Rhynoodle Ltd
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918,96,Thoughtmix Ltd
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740,8,Amerisourc Corp
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852,42,Colgate-Pa Group
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270,73,Deseret Group
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64099,SO - 0007573,2018-02-28,74,Wholesale,USD,AXW291,825,26,12,1815.7,21788.4,980.478,74,Dazzlesphe Corp
64100,SO - 0007706,2018-02-28,51,Export,USD,NXH382,444,21,6,864.3,5185.8,579.081,51,Yombu Corp
64101,SO - 0007718,2018-02-28,136,Distributor,USD,AXW291,312,13,11,3953.0,43483.0,2648.510,136,Bath Group
64102,SO - 0008084,2018-02-28,158,Distributor,USD,AXW291,737,20,7,3959.7,27717.9,2930.178,158,Linklinks Ltd
64103,SO - 0008654,2018-02-28,22,Distributor,USD,AXW291,807,15,8,998.3,7986.4,848.555,22,SAFEWAY Ltd

In [29]:
# merge with products
df = df.merge(
    df_products,
    how = 'left',
    left_on = 'Product Description Index',
    right_on = 'Index'
)
df.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost,Customer Index,Customer Names,Index,Product Name
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343,126,Rhynoodle Ltd,27,Product 27
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918,96,Thoughtmix Ltd,20,Product 20
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740,8,Amerisourc Corp,26,Product 26
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852,42,Colgate-Pa Group,7,Product 7
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270,73,Deseret Group,8,Product 8

In [30]:
# merge with regions
df = df.merge(
    df_regions,
    how = 'left',
    left_on = 'Delivery Region Index',
    right_on = 'id'
)
df.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,type,latitude,longitude,area_code,population,households,median_income,land_area,water_area,time_zone
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,City,32.08354,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,City,39.61366,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,City,37.66243,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,City,39.16533,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,Town,41.77524,-72.52443,959,58007,24141,63158,70972793,720300,America/New York

In [31]:
# merge with State Regions
df = df.merge(
    df_state_reg[["State Code", "Region"]],
    how = 'left',
    left_on = 'state_code',
    right_on = 'State Code'
)
df.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,longitude,area_code,population,households,median_income,land_area,water_area,time_zone,State Code,Region
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York,GA,South
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,IN,Midwest
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles,CA,West
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,IN,Midwest
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,-72.52443,959,58007,24141,63158,70972793,720300,America/New York,CT,Northeast

In [32]:
# merging with budgets

df = df.merge(
    df_budgets,
    how='left',
    on = 'Product Name'
)

In [33]:
df.to_csv(r"D:\Data Analytics\End to End Data analytics Project\df_file.csv", index = False)

# Step 8: Clean Up Redundant Columns

After merging multiple tables (Sales, Customers, Products, Regions), we often end up with **duplicate or technical ID columns** that are no longer needed for analysis or visualization.

In this step, we'll drop the following columns:

- `Customer Index` → already merged, we can keep the name instead
- `Index` → from product table merge
- `id` → often an internal row ID
- `State Code` → used for joining, not needed in visuals

This helps **declutter the DataFrame** and makes it easier to work with.

In [36]:
df.drop(columns=[
    'Customer Index',
    'Index',
    'id',
    'State Code'
], inplace=True)
df.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,...,longitude,area_code,population,households,median_income,land_area,water_area,time_zone,Region,2017 Budgets
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York,South,964940.231
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,Midwest,2067108.120
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles,West,5685138.270
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,Midwest,889737.555
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,-72.52443,959,58007,24141,63158,70972793,720300,America/New York,Northeast,1085037.329

# Step 9: Standardize Column Headers to Snake Case

To make our column names easier to work with in Python, we convert them all to **snake_case** format:
- All lowercase
- Spaces and dashes replaced with underscores
- Leading/trailing spaces removed

This improves readability and reduces errors when referencing column names in code.

In [38]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(' ', '_')
        .str.replace('-', '_')
    )
    return df

In [39]:
df = clean_columns(df)

In [40]:
df.head()

,ordernumber,orderdate,customer_name_index,channel,currency_code,warehouse_code,delivery_region_index,product_description_index,order_quantity,unit_price,...,longitude,area_code,population,households,median_income,land_area,water_area,time_zone,region,2017_budgets
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,...,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York,South,964940.231
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,...,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,Midwest,2067108.120
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,...,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles,West,5685138.270
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,...,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,Midwest,889737.555
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,...,-72.52443,959,58007,24141,63158,70972793,720300,America/New York,Northeast,1085037.329

In [49]:
import pandas as pd
pd.set_option('display.max_columns', None)
df

,ordernumber,orderdate,customer_name_index,channel,currency_code,warehouse_code,delivery_region_index,product_description_index,order_quantity,unit_price,line_total,total_unit_cost,customer_names,product_name,name,county,state_code,state,type,latitude,longitude,area_code,population,households,median_income,land_area,water_area,time_zone,region,2017_budgets
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343,Rhynoodle Ltd,Product 27,Savannah,Chatham County,GA,Georgia,City,32.08354,-81.09983,912,145674,52798,36466,268318796,13908113,America/New York,South,964940.231
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918,Thoughtmix Ltd,Product 20,Greenwood,Johnson County,IN,Indiana,City,39.61366,-86.10665,317,55586,20975,54176,72276415,1883,America/Indiana/Indianapolis,Midwest,2067108.120
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740,Amerisourc Corp,Product 26,Pleasanton,Alameda County,CA,California,City,37.66243,-121.87468,925,79510,26020,124759,62489257,386195,America/Los Angeles,West,5685138.270
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852,Colgate-Pa Group,Product 7,Bloomington,Monroe County,IN,Indiana,City,39.16533,-86.52639,812,84067,30232,30019,60221613,475857,America/Indiana/Indianapolis,Midwest,889737.555
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270,Deseret Group,Product 8,Manchester,Hartford County,CT,Connecticut,Town,41.77524,-72.52443,959,58007,24141,63158,70972793,720300,America/New York,Northeast,1085037.329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64099,SO - 0007573,2018-02-28,74,Wholesale,USD,AXW291,825,26,12,1815.7,21788.4,980.478,Dazzlesphe Corp,Product 26,Levittown,Bucks County,PA,Pennsylvania,CDP,40.15511,-74.82877,445,51326,18095,69878,26311722,253129,America/New York,Northeast,5685138.270
64100,SO - 0007706,2018-02-28,51,Export,USD,NXH382,444,21,6,864.3,5185.8,579.081,Yombu Corp,Product 21,Palatine,Cook County,IL,Illinois,Village,42.11030,-88.03424,847,69308,26242,71573,35271964,370235,America/Chicago,Midwest,959899.218
64101,SO - 0007718,2018-02-28,136,Distributor,USD,AXW291,312,13,11,3953.0,43483.0,2648.510,Bath Group,Product 13,Margate,Broward County,FL,Florida,City,26.24453,-80.20644,954,57234,20651,42786,22943340,594611,America/New York,South,3720639.645
64102,SO - 0008084,2018-02-28,158,Distributor,USD,AXW291,737,20,7,3959.7,27717.9,2930.178,Linklinks Ltd,Product 20,Cheektowaga,Erie County,NY,New York,Town,42.91002,-78.74182,716,87514,38912,48662,76228647,162756,America/New York,Northeast,2067108.120
64103,SO - 0008654,2018-02-28,22,Distributor,USD,AXW291,807,15,8,998.3,7986.4,848.555,SAFEWAY Ltd,Product 15,Beaverton,Washington County,OR,Oregon,City,45.48706,-122.80371,503,96577,37238,56882,50563936,0,America/Los Angeles,West,3299478.315

# Step 10: Keep Only the Relevant Columns

After merging and cleaning multiple sheets, the dataset contains several technical or intermediate columns that are not required for final analysis.

In this step, we define a list of **important columns** to retain and drop everything else. These columns cover:

- Order details (date, number, quantity, price)
- Customer and product info
- Geographic and regional data
- 2017 budget values

This helps streamline the dataset for focused and efficient analysis.

In [57]:
cols_to_keep = [
    'ordernumber',
    'orderdate',
    'customer_names',
    'channel',
    'product_name',
    'order_quantity',
    'unit_price',
    'line_total',
    'total_unit_cost',
    'state_code',
    'county',
    'state',
    'region',
    'latitude',
    'longitude',
    '2017_budgets'
]

In [61]:
df = df[cols_to_keep]
df.head()

,ordernumber,orderdate,customer_names,channel,product_name,order_quantity,unit_price,line_total,total_unit_cost,state_code,county,state,region,latitude,longitude,2017_budgets
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Chatham County,Georgia,South,32.08354,-81.09983,964940.231
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Johnson County,Indiana,Midwest,39.61366,-86.10665,2067108.120
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,Alameda County,California,West,37.66243,-121.87468,5685138.270
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Monroe County,Indiana,Midwest,39.16533,-86.52639,889737.555
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Hartford County,Connecticut,Northeast,41.77524,-72.52443,1085037.329

In [74]:
df.rename(columns={'orderdate': 'order_date',
                   'ordernumber': 'order_number',
                  'line_total': 'revenue',
                  'total_unit_cost': 'cost',
                   'state': 'state_name',
                   'latitude': 'lat',
                   'longitude': 'lon',
                   '2017_budgets': 'budget'
                  }, inplace=True)

In [76]:
df.head()

,order_number,order_date,customer_names,channel,product_name,order_quantity,unit_price,revenue,cost,state_code,county,state_name,region,lat,lon,budget
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Chatham County,Georgia,South,32.08354,-81.09983,964940.231
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Johnson County,Indiana,Midwest,39.61366,-86.10665,2067108.120
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,Alameda County,California,West,37.66243,-121.87468,5685138.270
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Monroe County,Indiana,Midwest,39.16533,-86.52639,889737.555
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Hartford County,Connecticut,Northeast,41.77524,-72.52443,1085037.329

In [71]:
df.to_csv(r"D:\Data Analytics\End to End Data analytics Project\df_file5.csv", index = False)

# Step 11: Blank Out Budgets for Non-2017 Orders

The `budget` column in our dataset is only relevant for the year **2017**.

To avoid misleading analysis, we will set the `budget` values to blank (missing) for all orders that do **not belong to 2017**.

This ensures that comparisons between actual revenue and budget are accurate and only apply to the correct time period.

In [80]:
df.loc[df['order_date'].dt.year != 2017, 'budget'] = pd.NA

df[['order_date', 'product_name', 'revenue', 'budget']].head(5)

  order_date product_name  revenue  budget
0 2014-01-01   Product 27  14994.6     NaN
1 2014-01-01   Product 20  25868.7     NaN
2 2014-01-01   Product 26   5869.2     NaN
3 2014-01-01    Product 7  16368.1     NaN
4 2014-01-01    Product 8  18331.2     NaN

In [86]:
df.to_csv('final.csv',index = False)

In [90]:
df.to_csv(r"D:\Data Analytics\End to End Data analytics Project\sales_cleaned_final.csv", index=False)